# docker-compose.yml
version: "3"
services:
    napcat:
        environment:
            - ACCOUNT="3808139675"
            - WS_ENABLE=true
            - NAPCAT_UID=0
            - NAPCAT_GID=0
        ports:
            - 3001:3001
            - 6099:6099
        container_name: napcat
        network_mode: bridge
        restart: always
        image: mlikiowa/napcat-docker:latest
